version: '3'
services:
  foodie-app:
    build: .
    container_name: foodie-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://anwarulhaque321:anwarul321@mongodbcluster.grm0hf7.mongodb.net/foodie
      - PORT=4000

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
